### ISSUE TITLE
[Question] Why are the returns from GetUuid inconsistent between LvObject and VgObject?

### ISSUE THREAD

**Issue by crielly** [nak3/go-lvm#2]
```
INFO: 2018/03/04 18:14:33 lvm.go:49: Found VG matching name somevgname: 0x2513980
INFO: 2018/03/04 18:14:33 lvm.go:54: Found LV matching name somelvname: AZHvTc-Aeqs-Q8EG-JHwF-MSjw-Bs7k-Xkm8yb
```
Just wondering why the `LvObject.GetUuid()` seems to return the same UUID that `lvdisplay` does, but `VgObject.GetUuid()` returns something that looks like a memory address? VG return type is `*C.char` whereas LV return type is a string.

**Comment by nak3** [comment]
Hi @crielly

Thank you for interested in this proeject. But unfortunately I stopped developing this library due to the announcement of `lvm2app.h`'s deprecation. Please refer to my comment here:

https://github.com/nak3/go-lvm/issues/1#issuecomment-348683826

If you would like to use lvm2 library for golang, I think you should use dbus based library developing here:

  https://github.com/hetzneronline/go-lvm
